# Run like: cargo make [dev/release] 

###################
## Config        ##
###################

[config]
skip_core_tasks = true
default_to_workspace = false

[env]
DOCKER_BUILDKIT = "1"
CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true


env_files = ["./.env"]

##########################
##  GENERIC             ##
##########################
[tasks.make-paths]
script_runner = "@duckscript"
script = ["mkdir ./dist/contracts"] 

##########################
##  FRONTEND            ##
##########################

## Dev
[tasks.frontend-dev]
run_task = { name = [
    "frontend-run-dev-mediaserver",
    "frontend-run-dev-npm",
    "frontend-run-iframe-dev-npm",
], fork = true, parallel = true }

[tasks.frontend-run-dev-mediaserver]
script_runner = "@shell"
script = ["node ./frontend/local-media-server.js"]

[tasks.frontend-run-dev-npm]
script_runner = "@shell"
script = ["npm start"] 

[tasks.frontend-run-iframe-dev-npm]
script_runner = "@shell"
script = ["npm start"] 
cwd = "./frontend/iframe"

## Build
[tasks.frontend-build]
run_task = { name = [
    "frontend-build-npm",
    "frontend-build-iframe-npm",
]}

[tasks.frontend-build-npm]
script_runner = "@shell"
script = ["npm run build"] 


[tasks.frontend-build-iframe-npm]
script_runner = "@shell"
script = ["npm run build"] 
cwd = "./frontend/iframe"

##########################
##  CONTRACT - REGISTRY ##
##########################

[tasks.contract-registry-release]
run_task = { name = [
    "make-paths",
    "contract-registry-release-build",
    "contract-registry-release-optimize",
]}

[tasks.contract-registry-release-build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"]
cwd = "./contracts/registry"
env = { RUSTFLAGS = "-C link-arg=-s" }

[tasks.contract-registry-release-optimize]
command = "wasm-opt"
args = ["-Os", "./target/wasm32-unknown-unknown/release/contract_registry.wasm", "-o", "./dist/contracts/contract-registry.wasm"] 