# Run like: cargo make [dev/release] 

###################
## Config        ##
###################

[config]
skip_core_tasks = true
default_to_workspace = false

[env]
DOCKER_BUILDKIT = "1"
CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true


env_files = ["./.env"]

##########################
##  GENERIC             ##
##########################
[tasks.make-paths]
script_runner = "@duckscript"
script = ["mkdir ./frontend/media/contracts"] 

##########################
##  HIGH-LEVEL ALL      ##
##########################

[tasks.dev]
run_task = { name = [
    "frontend-dev",
    "contracts-dev",
], fork = true, parallel = true }

[tasks.build-release]
run_task = { name = [
    "frontend-build",
    "contracts-build-release",
    "build-copy-files",
]}

[tasks.frontend-build]
run_task = { name = [
    "frontend-build-npm",
    "frontend-build-iframe-npm",
]}

[tasks.contracts-build-release]
run_task = { name = [
    "contract-account-build-release",
]}

[tasks.contracts-test]
run_task = { name = [
    "contract-account-test",
]}

[tasks.build-copy-files]
script_runner = "@shell"
script = '''
cp ./dist/frontend/index.html ./dist/frontend/404.html
cp -R ./frontend/iframe/build/ ./dist/frontend/iframe/
cp -R ./frontend/media/ ./dist/frontend/media/
''' 

##########################
##  FRONTEND            ##
##########################

## Dev
[tasks.frontend-dev]
run_task = { name = [
    "frontend-run-dev-mediaserver",
    "frontend-run-dev-npm",
    "frontend-run-iframe-dev-npm",
], fork = true, parallel = true }

[tasks.frontend-run-dev-mediaserver]
script_runner = "@shell"
script = ["node ./frontend/local-media-server.js"]

[tasks.frontend-run-dev-npm]
script_runner = "@shell"
script = ["npm start"] 

[tasks.frontend-run-iframe-dev-npm]
script_runner = "@shell"
script = ["npm start"] 
cwd = "./frontend/iframe"

## Build

[tasks.frontend-build-npm]
script_runner = "@shell"
script = ["npm run build"] 


[tasks.frontend-build-iframe-npm]
script_runner = "@shell"
script = ["npm run build"] 
cwd = "./frontend/iframe"

##########################
##  CONTRACT - REGISTRY ##
##########################

[tasks.contract-account-dev]
command = "watchexec"
args = ["-w", "./contracts/account", "cargo make contract-account-build-release"]

[tasks.contract-account-build-release]
run_task = { name = [
    "make-paths",
    "contract-account-compile-release",
    "contract-account-optimize-release",
    "contract-account-hash-release",
]}

[tasks.contract-account-compile-release]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"]
cwd = "./contracts/account"
env = { RUSTFLAGS = "-C link-arg=-s" }

[tasks.contract-account-optimize-release]
command = "wasm-opt"
args = ["-Os", "./target/wasm32-unknown-unknown/release/contract_account.wasm", "-o", "./frontend/media/contracts/contract-account.wasm"] 


[tasks.contract-account-hash-release]
script_runner = "@shell"
script = ["b3sum --no-names ./frontend/media/contracts/contract-account.wasm > ./frontend/media/contracts/contract-account-hash.txt"] 